# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1135342dc7de5ee4e1ffb7b7001def348f87d11aaf0e848287e3f212c2ddfb83f2154466fa5bccc7c3f8b9223f549b3be0db79e80d4be05bb6e838546b475499

test:
  secret_key_base: a052165bf7fcdeae1dbcd3435408034960db5c1aeca11473d411fedfbd37f5ef2e6e8bb19c78aba73020980ac8c6811439f34c4201a8cc9ac54de65b4d73519f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
